/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazCRUD;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Morochos
 */
public class Ver extends javax.swing.JFrame {

    /**
     * Creates new form Ver
     */
    public Ver() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Estudiantes = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        TxtNombre2 = new javax.swing.JTextField();
        Apellido2 = new javax.swing.JLabel();
        TxtApellido2 = new javax.swing.JTextField();
        Cedula2 = new javax.swing.JLabel();
        TxtCedula2 = new javax.swing.JTextField();
        Fecha2 = new javax.swing.JLabel();
        fecha2 = new javax.swing.JTextField();
        Telefono2 = new javax.swing.JLabel();
        Correo2 = new javax.swing.JLabel();
        TxtCorreo2 = new javax.swing.JTextField();
        lbImg12 = new javax.swing.JLabel();
        ImagenDelEstudiante = new javax.swing.JLabel();
        TxtTelefono2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Estudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/detalles.png"))); // NOI18N

        Nombre2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Nombre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nombre.png"))); // NOI18N
        Nombre2.setText("jLabel2");

        TxtNombre2.setBackground(new java.awt.Color(255, 255, 255));
        TxtNombre2.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        TxtNombre2.setBorder(null);
        TxtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombre2ActionPerformed(evt);
            }
        });

        Apellido2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Apellido2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Apellido.png"))); // NOI18N

        TxtApellido2.setBackground(new java.awt.Color(255, 255, 255));
        TxtApellido2.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        TxtApellido2.setBorder(null);

        Cedula2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cedula2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cedula.png"))); // NOI18N
        Cedula2.setText("jLabel2");

        TxtCedula2.setBackground(new java.awt.Color(255, 255, 255));
        TxtCedula2.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        TxtCedula2.setBorder(null);

        Fecha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fecha.png"))); // NOI18N

        fecha2.setBackground(new java.awt.Color(255, 255, 255));
        fecha2.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        fecha2.setBorder(null);
        fecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha2ActionPerformed(evt);
            }
        });

        Telefono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telefono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Telefono.png"))); // NOI18N

        Correo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Correo.png"))); // NOI18N

        TxtCorreo2.setBackground(new java.awt.Color(255, 255, 255));
        TxtCorreo2.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        TxtCorreo2.setBorder(null);

        lbImg12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImg12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ImagenDelEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imagendelestudiante.png"))); // NOI18N

        TxtTelefono2.setBackground(new java.awt.Color(255, 255, 255));
        TxtTelefono2.setFont(new java.awt.Font("Comfortaa", 0, 16)); // NOI18N
        TxtTelefono2.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Y");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(Estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbImg12, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(ImagenDelEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(TxtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Correo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Cedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Estudiantes)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(ImagenDelEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbImg12, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Telefono2)
                            .addComponent(TxtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Correo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha2ActionPerformed

    private void TxtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombre2ActionPerformed

    
    public  void llenar(int fila,int id){
        
       
        try{
            
            SimpleDateFormat s=new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date fechita;
            
            BufferedImage si;
            ImageIcon foto;
            
            Connection con= new Conexion().establecerConexion();
            ResultSet rs;
            
            PreparedStatement ps= con.prepareStatement("SELECT nombre,apellido,cedula,fecha,telefono,correo,foto FROM Estudiantes WHERE id=?");
            ps.setInt(1,id);
            
            rs=ps.executeQuery();
            
            while(rs.next()){
                
                 // Obtener los datos de la imagen del ResultSet
                InputStream inputStream = rs.getBinaryStream("foto");

                // Convertir la imagen en un array de bytes
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                byte[] buffer = new byte[4096];
                int bytesRead;
                while ((bytesRead = inputStream.read(buffer)) != -1) {
                    baos.write(buffer, 0, bytesRead);
                }
                byte[] imagenBytes = baos.toByteArray();

                // Obtener la longitud de bytes de la imagen
                int longitudBytes = imagenBytes.length;

                si = ImageIO.read(new ByteArrayInputStream(imagenBytes));

                foto = new ImageIcon(si);

                Image img = foto.getImage();
                Image newImg = img.getScaledInstance(lbImg12.getWidth(), lbImg12.getHeight(), java.awt.Image.SCALE_SMOOTH);

                ImageIcon newIcon = new ImageIcon(newImg);

                
                lbImg12.setIcon(newIcon);
                
                String nom=(rs.getString("nombre"));
                TxtNombre2.setEditable(false);
                String apellido=rs.getString("apellido");
                TxtNombre2.setText(nom+" "+apellido);
                
                TxtApellido2.setEditable(false);
                TxtCedula2.setText(rs.getString("cedula"));
                TxtCedula2.setEditable(false);
                
                String la_fecha= rs.getString("fecha");
                
                fecha2.setText(la_fecha);
               
                String telefono = rs.getString("telefono");
                String cuatroDigitos = telefono.substring(0, 4);
                String resto = telefono.substring(4);
                TxtTelefono2.setText(cuatroDigitos+"-"+resto);
                TxtTelefono2.setEditable(false);
                TxtCorreo2.setText(rs.getString("correo"));
                TxtCorreo2.setEditable(false);
                
                
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error"+e.toString());
       
        } catch (IOException ex) {
            Logger.getLogger(Pantalla1.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido2;
    private javax.swing.JLabel Cedula2;
    private javax.swing.JLabel Correo2;
    private javax.swing.JLabel Estudiantes;
    private javax.swing.JLabel Fecha2;
    private javax.swing.JLabel ImagenDelEstudiante;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Telefono2;
    private javax.swing.JTextField TxtApellido2;
    private javax.swing.JTextField TxtCedula2;
    private javax.swing.JTextField TxtCorreo2;
    private javax.swing.JTextField TxtNombre2;
    private javax.swing.JTextField TxtTelefono2;
    private javax.swing.JTextField fecha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImg12;
    // End of variables declaration//GEN-END:variables
}
